#=====================================================================================
# 彻底移除 opkg-utils 依赖，仅使用 rootfs 内置 opkg
#=====================================================================================

name: Build ImmortalWrt 24.10.2 for s905l3a

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      openwrt_board:
        description: "设备型号"
        required: false
        default: "s905l3a"
        type: choice
        options:
          - s905l3a
      openwrt_kernel:
        description: "内核版本"
        required: false
        default: "6.1.147_6.12.41-flippy-93+"
        type: choice
        options:
          - 6.1.147_6.12.41-flippy-93+

env:
  TZ: Asia/Shanghai
  ROOTFS_URL: "https://downloads.immortalwrt.org/releases/24.10.2/targets/armsr/armv8/immortalwrt-24.10.2-armsr-armv8-rootfs.tar.gz"
  PACKAGES_REPO: "https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_generic/"
  REQUIRED_DRIVERS: "kmod-usb-net kmod-usb-net-rtl8152 kmod-usb-net-rtl8153 kmod-usb-net-cdc-ether kmod-usb-net-asix kmod-usb-net-asix-ax88179 kmod-usb-net-rtl8812au kmod-usb-net-rtl88x2bu"
  MANAGE_IP: "192.168.11.1"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 基础环境准备
        run: |
          # 仅保留必要工具
          sudo apt-get update -y
          sudo apt-get install -y curl wget tar gzip lz4 cpio kmod
          sudo apt-get clean

      - name: 下载并处理 RootFS
        run: |
          # 创建工作目录
          mkdir -p openwrt/output
          cd openwrt/output

          # 下载 RootFS
          wget -q --show-progress "${ROOTFS_URL}" -O rootfs.tar.gz
          mkdir rootfs && tar -zxf rootfs.tar.gz -C rootfs

          # 修改软件源（使用内置 opkg）
          cat > rootfs/etc/opkg/distfeeds.conf <<
