#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Build ImmortalWrt 24.10.2 for s905l3a with dual kernels (彻底移除opkg-utils依赖)
#=====================================================================================

name: Build ImmortalWrt 24.10.2 for s905l3a

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "immortalwrt"
        type: choice
        options:
          - immortalwrt  # 仅保留immortalwrt源码
      openwrt_board:
        description: "Select device board"
        required: false
        default: "s905l3a"
        type: choice
        options:
          - s905l3a  # 仅保留目标设备
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.1.147_6.12.41-flippy-93+"
        type: choice
        options:
          - 6.1.147_6.12.41-flippy-93+  # 双内核组合
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: false  # 禁用自动内核，固定版本
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "tianteng888/flippy-kernels"  # 指定flippy内核仓库
        type: choice
        options:
          - tianteng888/flippy-kernels
          - ophub/kernel
      kernel_usage:
        description: "Set the tags of the kernel"
        required: false
        default: "neih"  # 对应flippy内核的tag
        type: choice
        options:
          - neih
          - stable
      openwrt_storage:
        description: "Select image storage type."
        required: false
        default: "save"
        type: choice
        options:
          - save
          - temp
      builder_name:
        description: "Set OpenWrt builder signature."
        required: false
        default: "custom-builder"
        type: choice
        options:
          - custom-builder
          - ophub

env:
  TZ: Asia/Shanghai
  # 固定版本资源地址
  IMMORTALWRT_VERSION: "24.10.2"
  ROOTFS_URL: "https://downloads.immortalwrt.org/releases
