#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Build OpenWrt using releases files (fixed chroot permission)
#=====================================================================================

name: Build OpenWrt using releases files

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "immortalwrt"
        type: choice
        options:
          - official
          - lede
          - immortalwrt
      openwrt_board:
        description: "Select device board"
        required: false
        default: "s905l3a"
        type: choice
        options:
          - s905l3a
          - s905l3a-cm311
          - s905l3a-m401a
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.12.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
      auto_kernel:
        description: "Auto use the latest kernel"
        required: false
        default: false
        type: boolean
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: "tianteng888/flippy-kernels"
        type: choice
        options:
          - ophub/kernel
          - tianteng888/flippy-kernels
      kernel_usage:
        description: "Set the tags of the kernel"
        required: false
        default: "neih"
        type: choice
        options:
          - stable
          - flippy
          - dev
          - beta
          - neih

env:
  TZ: Asia/Shanghai
  ROOTFS_URL: "https://downloads.immortalwrt.org/releases/24.10.2/targets/armsr/armv8/immortalwrt-24.10.2-armsr-armv8-rootfs.tar.gz"
  KERNEL_URL: "https://github.com/tianteng888/flippy-kernels/releases/download/neih/6.12.41-flippy-93+.tar.gz"

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        id: init
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl wget tar gzip xz-utils unzip build-essential \
            qemu-user-static binfmt-support pv lvm2
          # 启用binfmt支持（关键：确保qemu能模拟aarch64）
          sudo update-binfmts --enable qemu-aarch64
          sudo systemctl daemon-reload
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create simulated disk (with proper permissions)
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[a-zA-Z]//g') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[a-zA-Z]//g') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6 /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          # 挂载时添加权限选项，确保root可访问
          sudo mount -o defaults,uid=0,gid=0 /dev/github/runner /builder
          sudo chmod 755 /builder  # 确保目录权限正确

      - name: Download & verify rootfs
        id: download_rootfs
        working-directory: /builder
        run: |
          mkdir -p openwrt/rootfs
          sudo wget -c "${{ env.ROOTFS_URL }}" -O openwrt/rootfs.tar.gz
          
          if [ ! -f "openwrt/rootfs.tar.gz" ]; then
            echo "rootfs下载失败" && exit 1
          fi
          
          # 用root权限解压，确保文件所有者正确
          sudo tar -zxf openwrt/rootfs.tar.gz -C openwrt/rootfs
          rootfs_contents=$(ls openwrt/rootfs)
          if [ $(echo "$rootfs_contents" | wc -l) -eq 1 ] && [ -d "openwrt/rootfs/$rootfs_contents" ]; then
            sudo mv openwrt/rootfs/$rootfs_contents/* openwrt/rootfs/
            sudo rmdir openwrt/rootfs/$rootfs_contents
          fi
          
          # 查找opkg并确保权限
          OPKG_PATH=$(sudo find openwrt/rootfs -name "opkg" | grep -E "/usr/bin/opkg|/bin/opkg" | head -n 1)
          if [ -z "$OPKG_PATH" ]; then
            echo "错误：未找到opkg"
            sudo ls -la openwrt/rootfs/usr/bin
            sudo ls -la openwrt/rootfs/bin
            exit 1
          fi
          sudo chmod +x "$OPKG_PATH"  # 确保opkg可执行
          
          echo "找到opkg：$OPKG_PATH"
          echo "opkg_path=$OPKG_PATH" >> ${GITHUB_OUTPUT}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Configure opkg sources
        if: ${{ steps.download_rootfs.outputs.status }} == 'success'
        run: |
          OPKG_CONF="/builder/openwrt/rootfs/etc/opkg/distfeeds.conf"
          sudo mkdir -p $(dirname $OPKG_CONF)
          sudo tee $OPKG_CONF << EOF
          src/gz immortalwrt_core https://downloads.immortalwrt.org/releases/24.10.2/targets/armsr/armv8/packages
          src/gz immortalwrt_base https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_cortex-a53/base
          src/gz immortalwrt_luci https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_cortex-a53/luci
          src/gz immortalwrt_packages https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_cortex-a53/packages
          src/gz immortalwrt_routing https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_cortex-a53/routing
          src/gz immortalwrt_telephony https://downloads.immortalwrt.org/releases/24.10.2/packages/aarch64_cortex-a53/telephony
          EOF

      - name: Install USB Ethernet drivers (fixed chroot permission)
        if: ${{ steps.download_rootfs.outputs.status }} == 'success'
        run: |
          ROOTFS_DIR="/builder/openwrt/rootfs"
          # 挂载必要系统目录（确保以root执行）
          sudo mount -o bind /dev $ROOTFS_DIR/dev
          sudo mount -o bind /proc $ROOTFS_DIR/proc
          sudo mount -o bind /sys $ROOTFS_DIR/sys
          # 复制qemu模拟器并赋予执行权限
          sudo cp /usr/bin/qemu-aarch64-static $ROOTFS_DIR/usr/bin/
          sudo chmod +x $ROOTFS_DIR/usr/bin/qemu-aarch64-static
          
          # 关键：用sudo执行chroot，确保权限
          sudo chroot $ROOTFS_DIR /bin/sh -c "opkg update"
          sudo chroot $ROOTFS_DIR /bin/sh -c "opkg install \
            kmod-usb-net kmod-usb-net-rtl8150 kmod-usb-net-rtl8152 \
            kmod-usb-net-asix kmod-usb-net-asix-ax88179 kmod-usb-net-dm9601-ether \
            kmod-usb-net-smsc95xx kmod-usb2 kmod-usb3 kmod-usb-xhci-hcd"
          
          # 清理挂载（防止占用）
          sudo umount $ROOTFS_DIR/dev
          sudo umount $ROOTFS_DIR/proc
          sudo umount $ROOTFS_DIR/sys
          sudo rm -f $ROOTFS_DIR/usr/bin/qemu-aarch64-static

      - name: Download kernel
        id: download_kernel
        working-directory: /builder
        run: |
          mkdir -p openwrt/kernel
          sudo wget -c "${{ env.KERNEL_URL }}" -O openwrt/kernel/kernel.tar.gz
          if [ ! -f "openwrt/kernel/kernel.tar.gz" ]; then
            echo "内核下载失败" && exit 1
          fi
          sudo tar -zxf openwrt/kernel/kernel.tar.gz -C openwrt/kernel
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Package OpenWrt
        if: ${{ steps.download_kernel.outputs.status }} == 'success'
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: /builder/openwrt/rootfs
          openwrt_board: ${{ inputs.openwrt_board }}
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          kernel_path: /builder/openwrt/kernel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-s905l3a-24.10.2
          path: ${{ env.PACKAGED_OUTPUTPATH }}/*
          retention-days: 14
